export const KV_KEY="sonnet/latest.json",PUBLIC_SCHEMA_VERSION=2;
export const STATUSES=["seeking_team","forming_team","team_ready","writing","poem_complete","submission_pending","submitted","unknown"] as const;
export const STAGES=["LOOKING","INVITED","APPLIED","ROSTER","SIGNED","TEAM","WRITING","COMPLETE","SUBMITTED"] as const;
const statusSet=new Set<string>(STATUSES),stageSet=new Set<string>(STAGES),writingTypes=new Set(["writing_started","message","word_proposed","word_accepted","line_completed","poem_completed"]);
type JsonObject=Record<string,unknown>;
type PublicActivity={id:string;at:string;type:string;title:string;detail:string;game_id?:string;quote?:string};
export interface SonnetKvBinding{get(key:string,type:"text"):Promise<string|null>};export interface SonnetEnvironment{SONNET_PUBLIC_KV?:SonnetKvBinding};class ValidationError extends Error{}
function object(value:unknown):JsonObject{if(!value||typeof value!=="object"||Array.isArray(value))throw new ValidationError();return value as JsonObject}function text(value:unknown,max:number,empty=false):string{if(typeof value!=="string"||value.length>max||(!empty&&!value.trim()))throw new ValidationError();return value}function timestamp(value:unknown):string{const result=text(value,64);if(!Number.isFinite(Date.parse(result)))throw new ValidationError();return result}function count(value:unknown):number{if(!Number.isSafeInteger(value)||(value as number)<0)throw new ValidationError();return value as number}
function activity(raw:unknown,writing=false):PublicActivity{const item=object(raw);if(writing&&(typeof item.type!=="string"||!writingTypes.has(item.type)))throw new ValidationError();const clean:PublicActivity={id:text(item.id,32),at:timestamp(item.at),type:text(item.type,40),title:text(item.title,80),detail:text(item.detail,240)};if(item.game_id!==undefined)clean.game_id=text(item.game_id,80);if(item.quote!==undefined)clean.quote=text(item.quote,500);return clean}
function writing(value:unknown){if(value===null)return null;const source=object(value);if(!Number.isSafeInteger(source.version)||(source.version as number)<0||!Number.isSafeInteger(source.line_number)||(source.line_number as number)<0||(source.line_number as number)>14||!Array.isArray(source.lines)||source.lines.length>14||!Array.isArray(source.team)||source.team.length<1||source.team.length>8||!Array.isArray(source.activity)||source.activity.length>40)throw new ValidationError();const lines=source.lines.map(line=>text(line,1000,true)),team=source.team.map(alias=>text(alias,20));if(new Set(team).size!==team.length||!team.includes("Saruku")||team.some(alias=>alias!=="Saruku"&&!/^Teammate [A-G]$/.test(alias)))throw new ValidationError();const previous=source.previous_contributor===null?null:text(source.previous_contributor,20);if(previous!==null&&!team.includes(previous))throw new ValidationError();return{version:source.version as number,line_number:source.line_number as number,lines,previous_contributor:previous,team,activity:source.activity.map(item=>activity(item,true))}}
export function validatePublicSonnet(value:unknown){const source=object(value),schema=source.schema_version;if(schema!==1&&schema!==2)throw new ValidationError("schema");const mission=object(source.mission),counts=object(source.counts);if(typeof mission.status!=="string"||!statusSet.has(mission.status)||typeof mission.current_stage!=="string"||!stageSet.has(mission.current_stage)||!Array.isArray(source.recent_activity)||source.recent_activity.length>40)throw new ValidationError();const writingState=schema===1?null:writing(source.writing);return{schema_version:schema,checked_at:timestamp(source.checked_at),tracking_started_at:timestamp(source.tracking_started_at),mission:{title:text(mission.title,40),goal:text(mission.goal,100),deadline:text(mission.deadline,10),status:mission.status,current_stage:mission.current_stage,current_game:mission.current_game===null?null:text(mission.current_game,80)},counts:{direct_mentions:count(counts.direct_mentions),targeted_invites:count(counts.targeted_invites),reflex_replies:count(counts.reflex_replies),applications:count(counts.applications),rosters_with_saruku:count(counts.rosters_with_saruku),countersigns:count(counts.countersigns),teams_ready:count(counts.teams_ready),poems_completed:count(counts.poems_completed),submissions:count(counts.submissions)},recent_activity:source.recent_activity.map(item=>activity(item)),writing:writingState}}
export type PublicSonnet=ReturnType<typeof validatePublicSonnet>;function response(body:JsonObject,status:number,cache="no-store"){return Response.json(body,{status,headers:{"cache-control":cache,"content-type":"application/json; charset=utf-8","x-content-type-options":"nosniff"}})}export async function handleSonnetRequest(env:SonnetEnvironment):Promise<Response>{const kv=env?.SONNET_PUBLIC_KV;if(!kv||typeof kv.get!=="function")return response({error:"sonnet_data_unavailable"},503);let raw;try{raw=await kv.get(KV_KEY,"text")}catch{return response({error:"sonnet_data_temporarily_unavailable"},503)}if(raw===null)return response({error:"sonnet_data_not_found"},404);try{return response(validatePublicSonnet(JSON.parse(raw)),200,"public, max-age=60, stale-while-revalidate=300")}catch(error){return response({error:error instanceof ValidationError&&error.message==="schema"?"sonnet_schema_unsupported":"sonnet_data_invalid"},502)}}
