import assert from "node:assert/strict";
import test from "node:test";
import {KV_KEY,handleSonnetRequest,validatePublicSonnet} from "../src/server/sonnet-public.ts";
function fixture(status="seeking_team",stage="LOOKING"){return {schema_version:1,checked_at:"2026-09-14T12:00:00Z",tracking_started_at:"2026-09-14T10:00:00Z",mission:{title:"SONNET MISSION",goal:"Complete and submit one poem by Sep 18.",deadline:"2026-09-18",status,current_stage:stage,current_game:null},counts:{direct_mentions:0,targeted_invites:0,reflex_replies:0,applications:0,rosters_with_saruku:0,countersigns:0,teams_ready:0,poems_completed:0,submissions:0},recent_activity:[]}}
const binding=value=>({calls:[],async get(key,type){this.calls.push([key,type]);return value}});
test("valid schema is reconstructed from fixed read-only key",async()=>{const source=fixture();source.private_path="secret";const kv=binding(JSON.stringify(source));const response=await handleSonnetRequest({SONNET_PUBLIC_KV:kv});assert.equal(response.status,200);assert.deepEqual(kv.calls,[[KV_KEY,"text"]]);assert.equal(JSON.stringify(await response.json()).includes("private_path"),false)});
test("invalid KV documents fail safely",async()=>{assert.equal((await handleSonnetRequest({SONNET_PUBLIC_KV:binding("bad")})).status,502);const wrong=fixture();wrong.schema_version=2;assert.equal((await handleSonnetRequest({SONNET_PUBLIC_KV:binding(JSON.stringify(wrong))})).status,502)});
test("missing and failed KV reads expose no provider details",async()=>{assert.equal((await handleSonnetRequest({SONNET_PUBLIC_KV:binding(null)})).status,404);const response=await handleSonnetRequest({SONNET_PUBLIC_KV:{async get(){throw new Error("provider secret")}}});assert.equal(response.status,503);assert.equal((await response.text()).includes("provider secret"),false)});
test("formation and submitted schemas validate",()=>{const active=fixture("forming_team","ROSTER");active.mission.current_game="g";active.recent_activity=[{id:"evt_123",at:"2026-09-14T11:00:00Z",type:"roster",title:"Roster update",detail:"A proposed roster now includes Saruku.",game_id:"g"}];assert.equal(validatePublicSonnet(active).recent_activity[0].title,"Roster update");assert.equal(validatePublicSonnet(fixture("submitted","SUBMITTED")).mission.status,"submitted")});
test("private activity fields are stripped",()=>{const source=fixture();source.recent_activity=[{id:"evt_1",at:"2026-09-14T11:00:00Z",type:"replied",title:"Replied",detail:"Safe.",request_id:"private",did:"private",sig:"private"}];const encoded=JSON.stringify(validatePublicSonnet(source));assert.equal(encoded.includes("private"),false)});
