import assert from "node:assert/strict";
import test from "node:test";
import {readFileSync} from "node:fs";
import {createRequire} from "node:module";
import {pathToFileURL} from "node:url";
import ts from "typescript";
import {createElement} from "react";
import {renderToStaticMarkup} from "react-dom/server";
import {validatePublicSonnet} from "../src/server/sonnet-public.ts";
const require=createRequire(import.meta.url);const source=readFileSync(new URL("../src/components/sonnet-view.tsx",import.meta.url),"utf8");const compiled=ts.transpileModule(source,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext}}).outputText.replace('"react/jsx-runtime"',JSON.stringify(pathToFileURL(require.resolve("react/jsx-runtime")).href)).replace('"react"',JSON.stringify(pathToFileURL(require.resolve("react")).href)).replace('"../server/sonnet-public"',JSON.stringify(new URL("../src/server/sonnet-public.ts",import.meta.url).href));const {SonnetView}=await import("data:text/javascript;base64,"+Buffer.from(compiled).toString("base64"));
function fixture(status="seeking_team",stage="LOOKING"){return validatePublicSonnet({schema_version:1,checked_at:"2026-09-14T12:00:00Z",tracking_started_at:"2026-09-14T10:00:00Z",mission:{title:"SONNET MISSION",goal:"Complete and submit one poem by Sep 18.",deadline:"2026-09-18",status,current_stage:stage,current_game:status==="forming_team"?"g":null},counts:{direct_mentions:1,targeted_invites:2,reflex_replies:1,applications:1,rosters_with_saruku:1,countersigns:0,teams_ready:0,poems_completed:0,submissions:0},recent_activity:[{id:"evt_1",at:"2026-09-14T11:00:00Z",type:"team_invitation",title:"Team invitation",detail:"Saruku received a direct team invitation.",game_id:"g"}]})}
function writingFixture(status="writing",stage="WRITING"){const activities=Array.from({length:12},(_,index)=>({id:`evt_${index}`,at:`2026-09-14T11:${String(index).padStart(2,"0")}:00Z`,type:"message",title:index===0?"Teammate A":"Saruku",detail:"Team message.",quote:index===0?"<script>alert('x')</script>":`Message ${index}`}));return validatePublicSonnet({schema_version:2,checked_at:"2026-09-14T12:00:00Z",tracking_started_at:"2026-09-14T10:00:00Z",mission:{title:"SONNET MISSION",goal:"Complete and submit one poem by Sep 18.",deadline:"2026-09-18",status,current_stage:stage,current_game:"g"},counts:{direct_mentions:1,targeted_invites:2,reflex_replies:1,applications:1,rosters_with_saruku:1,countersigns:1,teams_ready:1,poems_completed:stage==="COMPLETE"?1:0,submissions:stage==="SUBMITTED"?1:0},recent_activity:[],writing:{version:8,line_number:3,lines:["First accepted line","Second accepted line"],previous_contributor:"Teammate A",team:["Saruku","Teammate A"],activity:activities}})}
const render=document=>renderToStaticMarkup(createElement(SonnetView,{initial:document}));
test("renders empty seeking state",()=>{const html=render(fixture());assert.match(html,/Looking for a team/);assert.match(html,/Recent activity/)});
test("renders active formation timeline",()=>{const html=render(fixture("forming_team","ROSTER"));assert.match(html,/Forming a team/);assert.match(html,/Team invitation/);assert.match(html,/Team · g/)});
test("renders submitted terminal state",()=>{const html=render(fixture("submitted","SUBMITTED"));assert.match(html,/Submitted/)});
test("writing makes current poem and latest ten activities visible",()=>{const html=render(writingFixture());assert.match(html,/Current poem/i);assert.match(html,/First accepted line/);assert.match(html,/Line 3 of 14/);assert.match(html,/Version 8/);assert.match(html,/Last contribution · Teammate A/);assert.match(html,/Live activity/i);assert.equal((html.match(/Team message\./g)||[]).length,10);assert.doesNotMatch(html,/Message 1</);assert.doesNotMatch(html,/did:key/)});
test("message HTML is escaped and poem remains at completion",()=>{const writing=render(writingFixture("poem_complete","COMPLETE"));assert.match(writing,/&lt;script&gt;alert/);assert.doesNotMatch(writing,/<script>/);assert.match(writing,/Second accepted line/);const submitted=render(writingFixture("submitted","SUBMITTED"));assert.match(submitted,/Current poem/i);assert.match(submitted,/Second accepted line/)});
test("polling preserves last data on failure",()=>{assert.match(source,/setInterval\(refresh,\s*60000\)/);assert.match(source,/catch\{if\(live\)setStale\(true\)\}/);assert.doesNotMatch(source,/catch[^}]*setDocument\(null\)/)});
